use template_db;

CREATE TRIGGER template_db.BEFORE_USER_INSERT
BEFORE INSERT ON USER
FOR EACH ROW
BEGIN
  SET NEW.CREATED_BY =  CURRENT_USER();
  SET NEW.UPDATED_BY = CURRENT_USER();
END;
-- drop trigger before_users_insert;

create table template_db.USER(
ID INT NOT NULL AUTO_INCREMENT,
USER_NAME VARCHAR(255),
EMAIL VARCHAR(255),
PASSWORD VARCHAR(255),
CREATED_BY VARCHAR(255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(255),
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
);
-- drop table user;


CREATE TRIGGER template_db.BEFORE_ROLE_INSERT
BEFORE INSERT ON ROLE
FOR EACH ROW
BEGIN
  SET NEW.CREATED_BY =  CURRENT_USER();
  SET NEW.UPDATED_BY = CURRENT_USER();
END;



CREATE TABLE template_db.ROLE(
ID INT NOT NULL,
ROLE_NAME VARCHAR(255) DEFAULT NULL,
CREATED_BY VARCHAR(255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(255),
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
);
-- drop table role;

-- drop table template_db.USER_ROLE;


CREATE TRIGGER template_db.BEFORE_USER_ROLE_INSERT
BEFORE INSERT ON USER_ROLE
FOR EACH ROW
BEGIN
  SET NEW.CREATED_BY = CURRENT_USER();
END;

CREATE TABLE template_db.USER_ROLE (
ROLE_ID INT NOT NULL,
USER_ID INT NOT NULL,
CREATED_BY VARCHAR(255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ROLE_ID, USER_ID),
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

-- drop table user_role;


CREATE TRIGGER template_db.BEFORE_MENU_INSERT
BEFORE INSERT ON MENU
FOR EACH ROW
BEGIN
  SET NEW.CREATED_BY =  CURRENT_USER();
  SET NEW.UPDATED_BY = CURRENT_USER();
END;

CREATE TABLE template_db.MENU(
PARENT_ID INT,
ID INT,
MENU_NAME VARCHAR(255),
CREATED_BY VARCHAR(255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(255),
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID),
FOREIGN KEY(PARENT_ID) REFERENCES MENU(ID)
);
-- drop table menu

CREATE TRIGGER template_db.BEFORE_HEADER_INSERT
BEFORE INSERT ON HEADER
FOR EACH ROW
BEGIN
  SET NEW.CREATED_BY =  CURRENT_USER();
  SET NEW.UPDATED_BY = CURRENT_USER();
END;

CREATE TABLE template_db.HEADER(
ID INT,
HEADER_NAME VARCHAR(255),
CREATED_BY VARCHAR(255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_BY VARCHAR(255),
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID)
);

CREATE TRIGGER template_db.BEFORE_HEADER__MENU_INSERT
BEFORE INSERT ON HEADER_MENU
FOR EACH ROW
BEGIN
  SET NEW.CREATED_BY =  CURRENT_USER();
END;

CREATE TABLE template_db.HEADER_MENU(
HEADER_ID INT,
MENU_ID INT,
CREATED_BY VARCHAR(255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(HEADER_ID,MENU_ID),
FOREIGN KEY (HEADER_ID) REFERENCES HEADER(ID),
FOREIGN KEY (MENU_ID) REFERENCES MENU(ID)
);

CREATE TABLE template_db.ROLE_HEADER(
HEADER_ID INT,
ROLE_ID INT,
PRIMARY KEY(HEADER_ID,ROLE_ID),
FOREIGN KEY(HEADER_ID) REFERENCES HEADER(ID),
FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID)
);

-- drop table role_header;




