INSERT INTO USER(USER_NAME,EMAIL,PASSWORD) VALUES('ASH','ASH@GMAIL.COM','ASD');

-- DELETE FROM USER;

-- delete from role;
INSERT INTO template_db.ROLE(ID,ROLE_NAME)VALUES(100,'user');
INSERT INTO template_db.ROLE(ID,ROLE_NAME)VALUES(101,'student');
INSERT INTO template_db.ROLE(ID,ROLE_NAME)VALUES(102,'faculty');

INSERT INTO template_db.MENU(PARENT_ID,ID,MENU_NAME)VALUES(NULL,500,"degrees and programs");
INSERT INTO template_db.MENU(PARENT_ID,ID,MENU_NAME)VALUES(500,600,"graduate programs");
INSERT INTO template_db.MENU(PARENT_ID,ID,MENU_NAME)VALUES(500,601,"undergraduate programs");
INSERT INTO template_db.MENU(PARENT_ID,ID,MENU_NAME)VALUES(NULL,501,"library");
INSERT INTO template_db.MENU(PARENT_ID,ID,MENU_NAME)VALUES(NULL,502,"catalog");
INSERT INTO template_db.MENU(PARENT_ID,ID,MENU_NAME)VALUES(502,602,"calendar");
INSERT INTO template_db.MENU(PARENT_ID,ID,MENU_NAME)VALUES(502,603,"courses");
INSERT INTO template_db.MENU(PARENT_ID,ID,MENU_NAME)VALUES(null,503,"upload assigment");
INSERT INTO template_db.MENU(PARENT_ID,ID,MENU_NAME)VALUES(null,504,"upload grade");

-- delete from menu where menu_id=500 ;

INSERT INTO template_db.HEADER(ID,HEADER_NAME)VALUES(300,'academics');
INSERT INTO template_db.HEADER(ID,HEADER_NAME)VALUES(301,'study materials');
INSERT INTO template_db.HEADER(ID,HEADER_NAME)VALUES(302,'assignment checker');

INSERT INTO template_db.HEADER_MENU(HEADER_ID,MENU_ID)VALUES(300,500);
INSERT INTO template_db.HEADER_MENU(HEADER_ID,MENU_ID)VALUES(301,502);
INSERT INTO template_db.HEADER_MENU(HEADER_ID,MENU_ID)VALUES(302,503);
INSERT INTO template_db.HEADER_MENU(HEADER_ID,MENU_ID)VALUES(302,504);

insert into ROLE_HEADER VALUES(300,100);
insert into ROLE_HEADER  VALUES(301,100);
insert into ROLE_HEADER VALUES(300,101);
insert into ROLE_HEADER VALUES(301,101);
insert into ROLE_HEADER VALUES(302,102);
